### ISSUE TITLE
使用leftwardMarqueeView，文本过多时，跑马灯就不起作用了

### ISSUE THREAD

**Issue by daniceda** [iceyouyou/UUMarqueeView#10]
类型为leftwardMarqueeView，文本超过500+，跑马灯就不显示了

**Comment by daniceda** [comment]
应该文字是超过lable显示的最长宽度的时候，就不显示了，这个能解决吗

**Comment by iceyouyou** [comment]
@daniceda 对这个问题做了一些测试：

【模拟器】
iPhone 6s (iOS 10.0) - 最多加载到799个中文字符，超出后不显示
iPhone 6s (iOS 11.4) - 最多加载到799个中文字符，超出后不显示
iPhone 8 Plus (iOS 11.4) - 最多加载到533个中文字符，超出后不显示

【真机】
iPhone X (iOS 11.4.1) - 至少可加载1w个中文字符，未继续测试上限
iPhone 6s Plus (iOS 12.1) - 至少可加载1w个中文字符，未继续测试上限

所以，在真机上可正常显示长文本，而在模拟器上文本过长可能造成显示异常。
目前没有发现代码层的问题，猜测是模拟器可支配资源有限导致的。

另外，如果要显示的文本过长，使用UITextView替换UILabel会有所改善，
这也是Apple开发文档提倡的做法。

> UILabel defines a label, which displays a static text string.
UITextField defines a text field, which displays a single line of editable text.
UITextView defines a text view, which displays multiple lines of editable text.
> 
> Although these classes actually can support the display of arbitrary amounts of text, 
labels and text fields are intended to be used for relatively small amounts of text, 
typically a single line. Text views, on the other hand, are meant to display large amounts of text.

[https://developer.apple.com/library/archive/documentation/StringsTextFonts/Conceptual/TextAndWebiPhoneOS/UsingTextClasses/UsingTextClasses.html](url)
