### ISSUE TITLE
我想让数据只滚动一遍就停止，但是设置stopWhenLessData=YES ，在Demo中没有效果 ，一直再循环滚动

### ISSUE THREAD

**Issue by 370966584** [iceyouyou/UUMarqueeView#13]

**Comment by iceyouyou** [comment]
@370966584 

stopWhenLessData=YES是在屏幕上已经显示出所有数据时（例如只有一条短数据）不滚动，而不是只滚动一次。

如果要滚动一次的效果，不修改代码的方法是在
```objective-c
- (void)updateItemView:(UIView*)itemView atIndex:(NSUInteger)index forMarqueeView:(UUMarqueeView*)marqueeView;
```
回调方法中根据即将要显示数据的index，调用pause方法停止滚动。
```objective-c
- (void)pause;
```

以Demo中第一个滚动条为例：
```objective-c
if (marqueeView == _upwardSingleMarqueeView) {
    // for upwardSingleMarqueeView
    ......

    static int scrollTimes = 0;
    if (index == 0) {
        scrollTimes++;
        if (scrollTimes == 2) {
            [_upwardSingleMarqueeView pause];	// 在第二次将要显示index为0的数据时停止
        }
    }
}
```

**Comment by 370966584** [comment]
> @370966584
> 
> stopWhenLessData=YES是在屏幕上已经显示出所有数据时（例如只有一条短数据）不滚动，而不是只滚动一次。
> 
> 如果要滚动一次的效果，不修改代码的方法是在
> 
> ```objc
> - (void)updateItemView:(UIView*)itemView atIndex:(NSUInteger)index forMarqueeView:(UUMarqueeView*)marqueeView;
> ```
> 
> 回调方法中根据即将要显示数据的index，调用pause方法停止滚动。
> 
> ```objc
> - (void)pause;
> ```
> 
> 以Demo中第一个滚动条为例：
> 
> ```objc
> if (marqueeView == _upwardSingleMarqueeView) {
>     // for upwardSingleMarqueeView
>     ......
> 
>     static int scrollTimes = 0;
>     if (index == 0) {
>         scrollTimes++;
>         if (scrollTimes == 2) {
>             [_upwardSingleMarqueeView pause];	// 在第二次将要显示index为0的数据时停止
>         }
>     }
> }
> ```

多谢 已经解决了
