### ISSUE TITLE
UUMarqueeViewTouchReceiver 点击问题

### ISSUE THREAD

**Issue by VanishTan** [iceyouyou/UUMarqueeView#14]
![image](https://user-images.githubusercontent.com/16330554/53335734-3a8fd500-3937-11e9-8b8a-26b252c32fba.png)

我把控件放在UITableViewCell 滑动到这个cell的时候 手碰一下就触发了，

**Comment by VanishTan** [comment]
![image](https://user-images.githubusercontent.com/16330554/53336049-1aace100-3938-11e9-8228-4c7f2a32e03d.png)

**Comment by iceyouyou** [comment]
@VanishTan 

感谢你的反馈和改善建议！

之前把点击事件放在touchesBegan里是个偷懒的行为，可以回避这样一个常见操作带来的困扰：
```objective-c
用户手指按住某行不放，UUMarqueeView继续滚动，用户手指松开触发点击，但此时触发的已经不是最初按下的条目。
```

但显然还是没有考虑到把UUMarqueeView放在UIScrollView下滑动时的体验问题。

我已提交了更新，把点击事件放入touchesEnded，并在用户手指按住期间暂停了UUMarqueeView的滚动行为。

如果使用时有问题，欢迎随时反馈，再次感谢！
