### ISSUE TITLE
设置为单行 UUMarqueeViewDirectionLeftward 滚动，要很久才开始滚动，这是为什么？

### ISSUE THREAD

**Issue by CCBrother** [iceyouyou/UUMarqueeView#15]
_marqueeView = [[UUMarqueeView alloc] initWithDirection:UUMarqueeViewDirectionLeftward];
        _marqueeView.delegate = self;
        _marqueeView.timeIntervalPerScroll = 1.0f;
        _marqueeView.timeDurationPerScroll = 0.5f;
        [self addSubview:_marqueeView];
        [_marqueeView reloadData];

**Comment by iceyouyou** [comment]
@CCBrother 
Demo里有UUMarqueeViewDirectionLeftward的示例，使用相同配置并没有出现滚动延时的问题。
单看这几行初始化是没问题的，检查一下别的地方。

猜测是数据源，如果数据源添加，请在数据源添加内容后再调用一下

**Comment by CCBrother** [comment]
是数据源问题，我先加载数据源后，再创建UUMarqueeView，就可以了

**Comment by iceyouyou** [comment]
不用重新创建，数据源加载数据后，再调用一下reloadData就行，像使用UITableView一样。

**Comment by CCBrother** [comment]
知道了，多谢~

**Comment by iceyouyou** [comment]
感谢支持，有问题欢迎随时反馈。

**Comment by CCBrother** [comment]
好的
