### ISSUE TITLE
放在tableViewCell里面的时候CPU占用率一直百分百

### ISSUE THREAD

**Issue by freesan44** [iceyouyou/UUMarqueeView#16]
TableView是用了SDAutoLayout进行Cell自动高度适配，只要在tableViewCell里面添加UUMarqueeView，一直滚动的话CPU占用率100%，除非进行tableView滑动【这个时候UUMarqueeView是停止滚动的】
用Time Profiler查找，是提示【scrollTimerDidFire】方法有问题

![WechatIMG1](https://user-images.githubusercontent.com/16640381/56492975-0fcd9180-6520-11e9-9af9-03a703281950.jpeg)

**Comment by iceyouyou** [comment]
简单改了一个把UUMarqueeView放在UITableViewCell上的例子，运行在iOS10.0和iOS12.1模拟器上的现象一致，都没有观察到CPU异常的情况。

使用UUMarqueeViewDirectionLeftward式样，无其它操作干扰情况下，CPU占用率0%
使用UUMarqueeViewDirectionUpward多行式样，无其它操作干扰情况下，CPU占用率0%-1%

能否把你的UUMarqueeView配置以及运行环境发给我，我再测试一下？

![屏幕快照 2019-04-23 上午10 22 51](https://user-images.githubusercontent.com/4847096/56548836-bfa00f00-65b3-11e9-901c-8fca4eb2fb5b.png)
![屏幕快照 2019-04-23 上午10 27 56](https://user-images.githubusercontent.com/4847096/56548861-cd559480-65b3-11e9-9282-015a9d256621.png)
