### ISSUE TITLE
从右向左滑，设置单个item的宽无效

### ISSUE THREAD

**Issue by jkwf** [iceyouyou/UUMarqueeView#17]
- (CGFloat)itemViewWidthAtIndex:(NSUInteger)index forMarqueeView:(UUMarqueeView*)marqueeView {
    // 指定条目在显示数据源内容时的视图宽度，仅[UUMarqueeViewDirectionLeftward]时被调用。
    // ### 在数据源不变的情况下，宽度可以仅计算一次并缓存复用。
    UILabel *content = [[UILabel alloc] init];
    content.font = [UIFont systemFontOfSize:10.0f];
    content.text = dataSource[index];
    return content.intrinsicContentSize.width;
}
这个方法执行了，但是每个item的宽还是和UUMarqueeView的大小一样
demo也是这种情况

**Comment by iceyouyou** [comment]
目前UUMarqueeView在横向滚动时的式样，代码内有限制，item最小宽度是UUMarqueeView控件的宽度。
这样可以确保新出现的item都是从UUMarqueeView右侧进入的效果。

**Comment by JhihPong** [comment]
你好，这个item最小宽度是否支持修改呢？

**Comment by jkwf** [comment]
> 你好，这个item最小宽度是否支持修改呢？

你看作者上面的恢复，只能通过修改UUMarqueeView控件的宽度来控制item宽度
