### ISSUE TITLE
xib引入问题

### ISSUE THREAD

**Issue by xiaoxem** [iceyouyou/UUMarqueeView#19]
你好，我使用xib 将view class类型改成UUMarqueeView，然后直接拖拽到vc中，程序运行起来之后发现并无数据显示。查看图层分析，itemview并未插入到UUMarqueeView中。
UUMarqueeView下并无其他自视图，请问是哪里有问题，UUMarqueeView只能直接创建声明使用吗？

**Comment by iceyouyou** [comment]
@xiaoxem 你好，我之前漏掉了xib使用的init方法，已经补上了，更新一下代码应该就好了。

**Comment by xiaoxem** [comment]
好的哦 谢谢
对了，从下往上滚动的时候，设置间隔分别是1.0 1.0 ，跑起来会有一顿一顿的感觉，请问要怎么设置，让其可以连贯的滚动

**Comment by iceyouyou** [comment]
因为滚动动画是缓入缓出（EaseInOut）的效果，所以即使滚动间隔设为0也会有停顿的感觉。不过我觉得连续滚动的需求是应该有的，而且并不难实现，稍后我会更新上这个功能。

**Comment by iceyouyou** [comment]
@xiaoxem 可以更新一下代码，现在滚动间隔（timeIntervalPerScroll）设置为0.0时，会自动切换为线性滚动动画。

**Comment by xiaoxem** [comment]
可以了，谢谢！
