### ISSUE TITLE
多行滚动时暂停延迟

### ISSUE THREAD

**Issue by doyouremember1** [iceyouyou/UUMarqueeView#22]
多行滚动时，点击暂停，会延迟一下，然后再停止

**Comment by iceyouyou** [comment]
暂停时会等到本次滚动结束后才停止，不会停在一半的状态。

**Comment by doyouremember1** [comment]
请问一下有没有办法可以立即停止？我用removeAllAnimation方法，会停止，但是下面的item的frame不对，会出现重叠的状况？请您回答一下，万分感激

**Comment by doyouremember1** [comment]
您好，我现在有这样的问题，比如一个多行滚动，某个item的长度比较长，要好10行才能展示的下，但是滚动框比较矮，一屏显示5行，暂停的时候读完这一屏，读完继续滚动，去阅读下一屏内容。暂停只会使item里的10行全部滚动万才能停止。不知道我表述的是否明白。

**Comment by iceyouyou** [comment]
明白你的问题，但现在是不支持立即停止的。初步考虑了一下，现有代码结构要实现你的需求稍微有点复杂。之后可能会做修改，但暂时不会有任何完成时间上的承诺。你去找找其他的第三方控件吧。

**Comment by doyouremember1** [comment]
好的，不过还是谢谢您
