### ISSUE TITLE
给定显示宽度后，不超出这个宽度，短文案 也会滚动，这个能控制吗？

### ISSUE THREAD

**Issue by shLuckySeven** [iceyouyou/UUMarqueeView#23]

**Comment by shLuckySeven** [comment]
left样式，只有一条文案，并且这条文案比较短的时候，内部能否处理为不滑动，只有当这条文本超出一行的时候才滚动？

**Comment by iceyouyou** [comment]
BOOL stopWhenLessData;    // do not scroll when all data has been shown
@shLuckySeven 这个属性设置为YES试试
