### ISSUE TITLE
bug，重复创建问题？

### ISSUE THREAD

**Issue by shLuckySeven** [iceyouyou/UUMarqueeView#24]
- (void)createItemView:(UIView*)itemView forMarqueeView:(UUMarqueeView*)marqueeView；这个代理，会连续执行3次，里面你 全是 alloc init，是故意这么写的吗 ？

**Comment by iceyouyou** [comment]
@shLuckySeven 是的，为了形成循环滚动效果，实际itemView的个数是visibleItemCount+2
