### ISSUE TITLE
文字超过屏幕宽度，显示...

### ISSUE THREAD

**Issue by yanqiangS** [iceyouyou/UUMarqueeView#25]
![image](https://user-images.githubusercontent.com/16951446/77981875-91878b00-733d-11ea-86e4-3170da2edf52.png)

**Comment by iceyouyou** [comment]
@yanqiangS 调整delegate中设置itemView宽度的回调，宽度计算正确就可以显示全。
```objective-c
- (CGFloat)itemViewWidthAtIndex:(NSUInteger)index forMarqueeView:(UUMarqueeView*)marqueeView;
```
