### ISSUE TITLE
横向滑动时item最小宽度是否支持修改？

### ISSUE THREAD

**Issue by JhihPong** [iceyouyou/UUMarqueeView#26]
横向滑动时item最小宽度是否支持修改？

**Comment by iceyouyou** [comment]
@JhihPong 横向滚动时item宽度最小为UUMarqueeView控件的宽度。即使在指定宽度的回调中返回了小于控件的宽度，也会被修正为与控件等宽。

试想一下如果item支持任意宽度的话，当宽度都很小的时候，新出现的item将可能凭空出现，而不是从控件右侧滑入。
