### ISSUE TITLE
UUMarqueeViewDirectionLeftward模式下

### ISSUE THREAD

**Issue by wmh8638** [iceyouyou/UUMarqueeView#28]
当数据源大于等于3条时 update代理方法返回的index和数据源对不上号 我想知道当前展示的index应该如何操作

**Comment by wmh8638** [comment]
- (void)updateItemView:(UIView*)itemView atIndex:(NSUInteger)index forMarqueeView:(UUMarqueeView*)marqueeView {
    // 设定即将显示的条目内容，在每次marquee view滑动时被调用。
    // 'index'即为数据源数组的索引值。
    UILabel *content = [itemView viewWithTag:1001];
    content.text = dataSource[index];
}

**Comment by wmh8638** [comment]
解决了 逻辑太复杂 有点看不懂 只有自己在动画结束时从数据源取出顺序正确的一条来reloadData 绕开了BUG 尴尬

**Comment by iceyouyou** [comment]
@wmh8638 这不是bug。

UUMarqueeViewDirectionLeftward式样下，@selector(updateItemView:atIndex:forMarqueeView:)回调方法中的
index不代表当前展示中那条数据的index。这是即将预加载数据的索引值，一般是当前展示数据的下下条，只需要
按照index取数据源赋值就可以了。（可以参考下Demo）

当一条数据左滑到控件最左侧边缘时，会调用@selector(updateItemView:atIndex:forMarqueeView:)开始预加载它
的下下条数据。这样的预加载机制是为了在View布局能够复用的机制下，确保滑动时数据间的无缝衔接。

**Comment by wmh8638** [comment]
需求是需要在每一条轮播有一个对应的label
轮播即将出现时 更换对应的label 对于更换label的时机大神有什么思路没有

发自我的iPhone

**Comment by iceyouyou** [comment]
@wmh8638
我理解你的需求只要正常使用就可以满足了。先确定数据源，在createItemView:forMarqueeView:回调中
创建UILabel，在updateItemView:atIndex:forMarqueeView:回调中使用数据源刷新UILabel。

**Comment by wmh8638** [comment]
我的label需要固定不动 而不是跟随跑马灯滚动 也就是说label创建在别的视图上 尴尬




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "youyou"<notifications@github.com&gt;; 
发送时间: 2020年7月30日(星期四) 晚上7:11
收件人: "iceyouyou/UUMarqueeView"<UUMarqueeView@noreply.github.com&gt;; 
抄送: "今晚打老虎"<328096579@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [iceyouyou/UUMarqueeView] UUMarqueeViewDirectionLeftward模式下 (#28)





 
@wmh8638
 我理解你的需求只要正常使用就可以满足了。先确定数据源，在createItemView:forMarqueeView:回调中
 创建UILabel，在updateItemView:atIndex:forMarqueeView:回调中使用数据源刷新UILabel。

**Comment by iceyouyou** [comment]
@wmh8638 明白了，做的时候并没有考虑这样的需求。看了下代码，数据从控件右侧开始进入的时间点拿不到，
只可以拿到数据到达控件最左侧即将开始滑出的时间点。如果需要的话可以在下面的位置添加代码把index传出去。
```objective-c
// UUMarqueeView.m
#pragma mark - Timer & Animation(private)
- (void)scrollTimerDidFire:(NSTimer *)timer {
    ......
    dispatch_async(dispatch_get_main_queue(), ^() {
        if (_direction == UUMarqueeViewDirectionLeftward) {
            [self moveToNextDataIndex];
            ......
            [self moveToNextItemIndex];
                                    <<<------------ 数据到达控件最左侧时间点
        } else {
            ......
        }
    });
}
```
此时最左侧显示数据的index可以这样获取
```objective-c
_items[_firstItemIndex].tag
```

**Comment by wmh8638** [comment]
好的 感谢🙏

发自我的iPhone
