### ISSUE TITLE
如何不循环滚动

### ISSUE THREAD

**Issue by YongHuiBai** [iceyouyou/UUMarqueeView#29]
如何实现不循环滚动

**Comment by iceyouyou** [comment]
@YongHuiBai 默认没有实现这个功能。如果你用的是UUMarqueeViewDirectionLeftward模式，
可以参考[Issues28](https://github.com/iceyouyou/UUMarqueeView/issues/28#issuecomment-666879190)，在最后一条数据滑动到最左侧后，使用pause方法暂停。
