### ISSUE TITLE
有个BUG

### ISSUE THREAD

**Issue by 825342680** [iceyouyou/UUMarqueeView#4]
在UUMarqueeViewDirectionLeftward下，第二条数据比第一条长的时候，内容显示不全

**Comment by iceyouyou** [comment]
感谢反馈！我重现了bug，今天改过来。

**Comment by iceyouyou** [comment]
bug已经修复，再次感谢！ @825342680

**Comment by JC-Passerby** [comment]
一条数据很长的话也显示不全
