### ISSUE TITLE
请教下 点击事件为什么不能添加手势啊？

### ISSUE THREAD

**Issue by lzcdgit** [iceyouyou/UUMarqueeView#5]
请教下 点击事件为什么不能添加手势啊？
我看你代码是
- (void)touchesBegan:(NSSet *)touches withEvent:(UIEvent *)event {
    UITouch *touch = [touches anyObject];
    CGPoint touchLocation = [touch locationInView:self];
    if (_touchDelegate) {
        [_touchDelegate touchAtPoint:touchLocation];
    }
}
我试着给uilable 添加手势,但是总是无法点击。
    self.oneLB.userInteractionEnabled = YES;
       
        UIPanGestureRecognizer *pan1 =  [[UIPanGestureRecognizer alloc] initWithTarget:self action:@selector(pan1Click)];
        [self.oneLB addGestureRecognizer:pan1];
请问您知道原因么？

**Comment by iceyouyou** [comment]
在touchEnabled=YES的时候，UUMarqueeView上覆盖了一个UIView蒙层专门用于响应点击事件。

**Comment by iceyouyou** [comment]
当touchEnabled=YES时，UUMarqueeView上添加了一个蒙层View用于响应点击事件。
```objective-c
#pragma mark - Touch handler(private)
- (void)resetTouchReceiver {
    if (_touchEnabled) {
        if (!_touchReceiver) {
            self.touchReceiver = [[HXMarqueeViewTouchReceiver alloc] init];
            _touchReceiver.touchDelegate = self;
            [self addSubview:_touchReceiver];
        } else {
            // ...
        }
    } else {
        // ...
    }
}
```
然后在点击时根据点击位置下显示的Item，再进行点击回调。
```objective-c
#pragma mark - HXMarqueeViewTouchResponder(private)
- (void)touchAtPoint:(CGPoint)point {
    for (HXMarqueeItemView *itemView in _items) {
        if ([itemView.layer.presentationLayer hitTest:point]) {
            // ...
            break;
        }
    }
}
```
所以添加在UILabel上的手势没有触发，是因为上面还有一个蒙层。
如果你想自己处理事件响应，可以设置touchEnabled=NO，这样就不会有蒙层影响了，但同时也失去了点击事件回调。
