### ISSUE TITLE
这次更新后内存暴涨

### ISSUE THREAD

**Issue by wncios** [iceyouyou/UUMarqueeView#9]

**Comment by iceyouyou** [comment]
@wncios 我使用不同的模拟器及真机跑了一下现在版本和最初版本的Demo，
1.模拟器 iPhone5s iOS8.1
2.模拟器 iPhone6s iOS9.3
3.模拟器 iPhone7 iOS11.4
4.真机 iPhone8 iOS11.0
同环境下两个Demo的内存使用几乎是一致的，没有出现暴涨的情况。
只是在不同机型及iOS系统版本之间会有差异，但均在合理范围内。

如果你那里依然有问题，是否有更详细的信息能提供？
